name: R4S
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - comm=0.2.3
  - debugpy=1.8.17
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libedit=3.1.20250104
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - libkrb5=1.21.3
  - libsodium=1.0.20
  - libstdcxx=15.1.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - lmdb=0.9.31
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.5.3
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - platformdirs=4.4.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - bleach==6.2.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - filelock==3.19.1
      - flatbuffers==25.2.10
      - fsspec==2025.9.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.75.0
      - h5py==3.14.0
      - idna==3.10
      - jinja2==3.1.6
      - joblib==1.5.2
      - kaggle==1.5.12
      - kagglehub==0.3.13
      - keras==3.11.3
      - libclang==18.1.1
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - namex==0.1.0
      - networkx==3.4.2
      - numpy==2.1.3
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - opt-einsum==3.4.0
      - optree==0.17.0
      - pandas==2.3.2
      - pathlib==1.0.1
      - pillow==11.3.0
      - protobuf==5.29.5
      - python-slugify==8.0.4
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.5
      - rich==14.1.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sympy==1.14.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - text-unidecode==1.3
      - threadpoolctl==3.6.0
      - tomli==2.2.1
      - torch==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - triton==3.4.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - webencodings==0.5.1
      - werkzeug==3.1.3
      - wrapt==1.17.3
      - yapf==0.43.0
prefix: /root/miniconda3/envs/R4S
